dataset:
  augmentations: []
  img_size: 512
  test:
    batch_size: 16
    csv_path: /home/semyon/cardiomethry/ChestXrayIndex/test.csv
    shuffle: False
  train:
    batch_size: 16
    csv_path: /home/semyon/cardiomethry/ChestXrayIndex/train_small.csv
    shuffle: True
  transforms: []
  val:
    batch_size: 16
    csv_path: /home/semyon/cardiomethry/ChestXrayIndex/val.csv
    shuffle: False
model:
  final_activation: relu
  in_channels: 3
  load_state: 0
  name: Baseline
  target_points: [0]
name: default_name
system:
  num_gpu: 1
  num_workers: 4
testing:
  save_visuals: True
training:
  criterion: []
  dump_period: 5
  log_interval: 20
  num_epochs: 10
  optimizer: [{'lr': 0.001, 'name': 'RAdam'}]
  save_visuals: True
  scheduler: [{'name': 'StepLR', 'step_size': 10}]
