name: init_name
dataset:
  train:
    batch_size: 16
    csv_path: /home/semyon/cardiomethry/ChestXrayIndex/train.csv
    shuffle: True
  val:
    batch_size: 16
    csv_path: /home/semyon/cardiomethry/ChestXrayIndex/val.csv
    shuffle: False
  test:
    batch_size: 16
    csv_path: /home/semyon/cardiomethry/ChestXrayIndex/test.csv
    shuffle: False

  img_size: 512               # size image resized to before any other transformation

  augmentations:              # transforms applied only during train phase
    - name: OneOf
      p: 0.9
      augmentations:
        - name: Compose
          p: 0.5
          augmentations:
            - name: Resize
              height: 256
              width: 256
            - name: PadIfNeeded
              min_height: 512
              min_width: 512
              border_mode: 0          # 1 = cv2.BORDER_REPLICATE; 0 = cv2.BORDER_CONSTANT
              value: 0
            - name: ShiftScaleRotate
              shift_limit: 0.1
              scale_limit: [0.2, 0.5]
              rotate_limit: 15
              p: 1
              border_mode: 0          # 1 = cv2.BORDER_REPLICATE; 0 = cv2.BORDER_CONSTANT
              value: 0
        - name: Compose
          p: 0.5
          augmentations:
            - name: Resize
              height: 460
              width: 460
            - name: PadIfNeeded
              min_height: 512
              min_width: 512
              border_mode: 0          # 1 = cv2.BORDER_REPLICATE; 0 = cv2.BORDER_CONSTANT
              value: 0
            - name: ShiftScaleRotate
              shift_limit: 0.01
              scale_limit: 0.05
              rotate_limit: 15
              p: 1
              border_mode: 0
              value: 0
    - name: OneOf
      p: 0.7
      augmentations:
        - name: RandomBrightnessContrast
          brightness_limit: 0.1
          contrast_limit: 0.1
          p: 0.5
        - name: GaussNoise
          p: 0.5

  transforms:
    - name: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - name: ToTensorV2

model:
  final_activation: relu
  in_channels: 3
  load_state: 0
  name: Densenet121_1FC
  target_points: [0,1]

training:
  dump_period: 5
  num_epochs: 30
  save_visuals: True
  log_interval: 20
  optimizer:
    - name: RAdam
      lr: .001
      weight_decay: 0.001
  scheduler:
    - name: StepLR
      step_size: 10
      gamma: 0.1
    
testing:
  save_visuals: True


system:
  num_gpu: 1
  num_workers: 4

